# Generated by Django 6.0.5 on 2026-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Marathon', 'Marathon'), ('Fun Run', 'Fun Run'), ('Trail Run', 'Trail Run'), ('Night Run', 'Night Run')], max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
