# Generated by Django 6.0.5 on 2026-07-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Marathon', 'Marathon'), ('Fun Run 5k', 'Fun Run 5k'), ('Fun Run 10k', 'Fun Run 10k'), ('Trail Run', 'Trail Run'), ('Night Run', 'Night Run')], max_length=100),
        ),
    ]
