# Generated by Django 6.0.4 on 2026-04-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_faceembedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceembedding',
            name='bbox_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faceembedding',
            name='embedding_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
