# Generated by Django 6.0.4 on 2026-05-21 03:15

import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_faceembedding_bbox_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoevent',
            name='event_name',
            field=models.CharField(default='Colorun', help_text='Contoh: colorun atau milo', max_length=100),
        ),
        migrations.AlterField(
            model_name='photoevent',
            name='image',
            field=models.ImageField(upload_to=photos.models.upload_to_event),
        ),
    ]
