# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_photoevent_event_name_alter_photoevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceembedding',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_crops/'),
        ),
    ]
