# Generated by Django 6.0.5 on 2026-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('jenis_event', models.CharField(choices=[('Marathon', 'Marathon'), ('Fun Run', 'Fun Run'), ('Trail Run', 'Trail Run'), ('Night Run', 'Night Run')], default='Marathon', max_length=20)),
                ('lokasi', models.CharField(max_length=100)),
                ('tanggal_event', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=100)),
                ('gambar', models.ImageField(upload_to='foto/')),
                ('timestamp', models.DateTimeField()),
                ('jenis_event', models.CharField(choices=[('Marathon', 'Marathon'), ('Fun Run', 'Fun Run'), ('Trail Run', 'Trail Run'), ('Night Run', 'Night Run')], default='Marathon', max_length=20)),
            ],
        ),
    ]
