# Generated by Django 6.0.5 on 2026-07-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_alter_event_jenis_event_alter_foto_jenis_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
